name: CI/CD Pipeline
on:
 push:
  branches: main

jobs:
 first_action:
  runs-on: ubuntu-latest
  steps:
   - name: checkout code
     uses: actions/checkout@v4
     
   - name: Installation NodeJS
     uses: actions/setup-node@v4
     with:
      node-version: 22
      
   - name: installing dependency
     shell: bash
     run: |
      npm ci
   - name: executing test
     shell: bash
     run: |
      npm run test
      ls -lart
 deploy:
  runs-on: ubuntu-latest
  steps:
   - name: checkout code
     uses: actions/checkout@v4
     
   - name: Installation NodeJS
     uses: actions/setup-node@v4
     with:
      node-version: 22
      
   - name: installing dependency
     shell: bash
     run: |
      npm ci
   - name: build the project
     shell: bash
     run: |
      npm run build
      ls -lart
      echo "deploying the application"
   


     
 
