name: CI/CD Pipeline

on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: print greetings
        shell: pwsh
        run: |
         Write-Host "this is the first individual workflows"
         Write-Host "you can do it Pratik, go ahead and conqure it"
