name: CI/CD pipeline
on: workflow_dispatch

jobs:
 killgrave:
   runs-on: ubuntu-latest

   steps:
     - name: first write-host command
       shell: pwsh
       run: |
        write-host "test this script pratik"
