name: CI/CD pipeline
on: workflow_dispatch
jobs:
 step-first:
  runs-on: ubuntu-latest
  steps:
   - name: test the pipe
     shell: pwsh
     run: | 
      Write-Host "test the pipe"
      pwsh --version
