name: CI/CD Pipeline
on:
 push:
  branches: main

jobs:
 first_action:
  runs-on: ubuntu-latest
  steps:
   - name: checkout code
     uses: actions/checkout@v4
     
   - name: Installation NodeJS
     uses: actions/setup-node@v4
     with:
      node-version: 22
      
   - name: display the content
     shell: bash
     run: |
      ls -lart
      node -v 
      npm -v

     
 
